version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: ephemr
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
